// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function GetColour(colour: $models.Colour): Promise<string> & { cancel(): void } {
    let $resultPromise = $Call.ByID(4215640907, colour) as any;
    return $resultPromise;
}

export function HexToRGB(hex: string): Promise<$models.RGBA> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3793569354, hex) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType0($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

// Private type creation functions
const $$createType0 = $models.RGBA.createFrom;
