// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreatePayload() {
  return window['go']['main']['App']['CreatePayload']();
}

export function PayloadToArray(arg1) {
  return window['go']['main']['App']['PayloadToArray'](arg1);
}
