// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreatePayload():Promise<main.Payload>;

export function PayloadToArray(arg1:main.Payload):Promise<Array<string>>;
