// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Create as $Create} from "@wailsio/runtime";

export class RGBA {
    "Red": number;
    "Green": number;
    "Blue": number;
    "Alpha": number;

    /** Creates a new RGBA instance. */
    constructor($$source: Partial<RGBA> = {}) {
        if (!("Red" in $$source)) {
            this["Red"] = 0;
        }
        if (!("Green" in $$source)) {
            this["Green"] = 0;
        }
        if (!("Blue" in $$source)) {
            this["Blue"] = 0;
        }
        if (!("Alpha" in $$source)) {
            this["Alpha"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RGBA instance from a string or object.
     */
    static createFrom($$source: any = {}): RGBA {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RGBA($$parsedSource as Partial<RGBA>);
    }
}
